name: DeployToGithubPages

on:
	push:
 		branches: [main]
jobs:
	deploy-to-github-pages:
 		runs-on: ubuntu-latest
   		steps:
            - uses: actions/checkout@v2  
			
            - name: Setup .NET Core SDK
            - name: copy index.html to 404.html
			  run: cp release/wwwroot/index.html release/wwwroot/404.html
	 
			- name: Deploy to Github Pages
		      uses: waihovong/github-pages-deploy-action@releases/v3
			 with:
		        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
		        BASE_BRANCH: master # The branch the action should deploy from.
		        BRANCH: gh-pages # The branch the action should deploy to.
		        FOLDER: build/wwwroot # The folder the action should deploy.
		        SINGLE_COMMIT: true
