name: build test and deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  deploy-to-github-pages:
  # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
    steps:
        - uses: actions/checkout@v4
        - name: Setup .NET Core SDK
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 8.0.x
        - name: Install .NET WASM Build Tools
          run: dotnet workload install wasm-tools
        - name: Publish .NET Core Project
          run: dotnet publish ./FormulaOneTech/FormulaOneTech.csproj -c:Release -p:GHPages=true -o dist/Web --nologo
        # - name: Check where index is
        #   run: ls -R ./dist/Web
        - name: Change base-tag in index.html from / to FormulaOneTech
          run: sed -i 's/<base href="\/" \/>/<base href="\/FormulaOneTech\/" \/>/g' ./dist/Web/wwwroot/index.html
        - name: Add .nojekyll file
          run: touch ./dist/Web/wwwroot/.nojekyll
        - name: Commit wwwroot to GitHub Pages
          uses: peaceiris/actions-gh-pages@v4
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: gh-pages
            FOLDER: release/wwwroot
        
